name: Run ESLint on Pull Requests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
          node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: eslint src/ --ext .js
