name: Run ESLint on Pull Requests


on:
  pull_request:
    branches: [ master ]

  
  workflow_dispatch:


jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - run: npm install
      
      - name: Run ESLint
        run: npx eslint src/ --ext .js --fix
